POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json 

{
    "username": "root",
    "password": "1412"
}
###
GET http://localhost:3001/api/authentication HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyNzZjZTYyNTRlMGQzZjYyODZmZTBkMyIsImlhdCI6MTY1MTk1ODAxMH0.g_Gepyde6bc20q2VXOFltDoF4d8EcaLY_ecWNiryNp8
