GET http://localhost:3001/api/room
### 
GET http://localhost:3001/api/room/tung
###
POST http://localhost:3001/api/room HTTP/1.1
content-type: application/json 

{
    "username": "tung",
    "mapSize": 5,
    "diffNumChessSetting": {
        "diffNum": false,
        "player": 1
    },
    "minChess": 0,
    "maxTimesOutTimes": 1,
    "maxTimeOut": 120,
    "turnTime": 60
}

###
POST http://localhost:3001/api/room HTTP/1.1
content-type: application/json 

{
    "username": "vinh",
    "mapSize": 5,
    "diffNumChessSetting": {
        "diffNum": false,
        "player": 1
    },
    "minChess": 0,
    "maxTimesOutTimes": 1,
    "maxTimeOut": 120,
    "turnTime": 60
}

###

DELETE http://localhost:3001/api/room HTTP/1.1
content-type: application/json 

{
    "username": "tung"
}

###
PUT http://localhost:3001/api/room HTTP/1.1
Content-Type: application/json

{
    "players": ["tung", "vinh"],
    "mapSize": 5,
    "diffNumChessSetting": {
        "diffNum": false,
        "player": 1
    },
    "minChess": 0,
    "maxTimesOutTimes": 1,
    "maxTimeOut": 120,
    "turnTime": 60
}