POST http://localhost:3001/api/socket/move HTTP/1.1
content-type: application/json 

{
    "username": "vinh", 
    "target": "tung",
    "message": "12to23"
}

###
POST http://localhost:3001/api/socket/move HTTP/1.1
content-type: application/json 

{
    "username": "tung", 
    "target": "vinh",
    "message": "12to23"
}
###
POST http://localhost:3001/api/socket/pauseReq HTTP/1.1
content-type: application/json 

{
    "username": "vinh", 
    "target": "tung"
}
###
POST http://localhost:3001/api/socket/pauseRes HTTP/1.1
content-type: application/json 

{
    "username": "tung", 
    "target": "vinh",
    "response": "yes"
}

###
POST http://localhost:3001/api/socket/swap HTTP/1.1
content-type: application/json 

{
    "target": "tung"
}
###
POST http://localhost:3001/api/socket/swap HTTP/1.1
content-type: application/json 

{
    "target": "vinh"
}