###
GET http://localhost:3001/api/users
###
GET http://localhost:3001/api/users/root
###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json 

{
    "username": "root",
    "name": "root",
    "email": "example@mail.com",
    "password": "1"
}

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json 

{
    "username": "tung",
    "name": "Van The Tung",
    "email": "vanthetung@gmail.com",
    "password": "1"
}

###
PUT http://localhost:3001/api/users HTTP/1.1
content-type: application/json 

{
    "username": "root",
    "displayName": "root",
    "password": "1"
}